# generated by datamodel-codegen:
#   filename:  dotenv.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class DotenvSchema(BaseModel):
    DATASET_DIRECTORY: Optional[str] = Field('.', description='place to put data')
    OPENAI_API_KEY: str = Field(
        ..., examples=['sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']
    )
